import{a as b,S as w,i as p}from"./assets/vendor-bad0427b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const m=document.querySelector(".form-search"),q=document.querySelector(".form-input"),v=document.querySelector(".loader-container"),i=document.querySelector(".btn-load-more");function f(){v.style.display="none"}const S="41575459-699006cd61f4fecce9ea2d52d";let a=1,y,h=40,$={key:S,q:y,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:h};async function g(l,o){const c=new URLSearchParams($);try{const s=await b.get(`https://pixabay.com/api/?${c}`);f();const{hits:e,totalHits:t}=s.data,n=document.querySelector(".gallery"),u=new w(".gallery a",{captionType:"attr",captionsData:"alt",captionDelay:250,captionPosition:"bottom",close:!0,enableKeyboard:!0,docClose:!0});u.refresh(),o===1&&(n.innerHTML="");const L=e.reduce((d,r)=>d+`<li class="gallery-item">
              <a class="image-link link" href="${r.largeImageURL}">
              <img class="images" data-source="${r.largeImageURL}" alt="${r.tags}" src="${r.webformatURL}" width="360" height="200">
              </a>
              <div class="information">
              <p>Likes: ${r.likes}</p>
              <p>Views: ${r.views}</p>
              <p>Comments: ${r.comments}</p>
              <p>Downloads: ${r.downloads}</p>
        </div>
      </li>`,"");if(n.insertAdjacentHTML("beforeend",L),u.refresh(),o*h>=t)i.style.display="none",p.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});else{i.style.display="block";const d=document.querySelector(".image-link").getBoundingClientRect().height;window.scrollBy({top:d*2,behavior:"smooth"})}}catch(s){f(),p.error({title:"Error",message:s.message,position:"topRight"})}}m.addEventListener("submit",l=>{l.preventDefault();const o=q.value.trim();a=1,i.style.display="none",g(o,a),m.reset()});i.addEventListener("click",()=>{a+=1,g(y,a)});
//# sourceMappingURL=commonHelpers.js.map
