import{i as l,S as m}from"./assets/vendor-46aac873.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const d=document.querySelector(".loader-container"),c=document.querySelector(".form-search"),f=document.querySelector(".form-input");function h(){d.style.display="block"}function p(){d.style.display="none"}let u={key:"41575459-699006cd61f4fecce9ea2d52d",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0};function y(s){u.q=s;const n=new URLSearchParams(u);if(h(),s.length<=0){l.error({title:"Error",message:"Please, enter something to search!",position:"topRight"});return}fetch(`https://pixabay.com/api/?${n}`).then(r=>{if(p(),!r.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return r.json()}).then(({hits:r})=>{const i=document.querySelector(".gallery");if(r.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const e=new m(".gallery a",{captionType:"attr",captionsData:"alt",captionDelay:250,captionPosition:"bottom",close:!0,enableKeyboard:!0,docClose:!0});i.innerHTML="";const t=r.reduce((a,o)=>a+`<li class="gallery-item">
              <a class="image-link link" href="${o.largeImageURL}">
              <img class="images" data-source="${o.largeImageURL}" alt="${o.tags}" src="${o.webformatURL}" width="360" height="200">
              </a>
              <div class="information">
              <p>Likes: ${o.likes}</p>
              <p>Views: ${o.views}</p>
              <p>Comments: ${o.comments}</p>
              <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`,"");i.insertAdjacentHTML("beforeend",t),e.refresh()}).catch(r=>{l.error({title:"Error",message:r.message,position:"topRight"})})}c.addEventListener("submit",s=>{s.preventDefault();const n=f.value.trim();y(n),c.reset()});
//# sourceMappingURL=commonHelpers.js.map
